### ISSUE TITLE
Static multiline subtitles

### ISSUE THREAD

**Issue by mazvydasb** [Daltron/NotificationBanner#14]
Hi @Daltron,

Very cool library! While implementing it we found that currently it's not possible to have multi-line subtitles instead of scrolling ones. Would it be possible to add a functionality for a static multi-line subtitles?

Thanks, 
Mazvydas

**Comment by Daltron** [comment]
Hi @mazvydasb! 😄

 I'm glad to hear you are enjoying the library. Unfortunately at this time, it's not possible to have multi-line subtitles unless you go the custom view route. This is due to the way [MarqueeLabel](https://github.com/cbpowell/MarqueeLabel) is implemented as it only supports one line labels since its sole purpose and existence is to scroll labels (which makes sense for that library not to support). This may be something I consider to add in the future though!
