### ISSUE TITLE
using from Objective-c

### ISSUE THREAD

**Issue by bhartsb** [Daltron/NotificationBanner#3]
I'm attempting to use this from Objective-c.   Running into problems though with BannerStyle enum and trying to instantiate a StatusBarNotificationBanner.  

Any pointers would be appreciated.

**Comment by Daltron** [comment]
Hi @bhartsb! 😄 

Unfortunately, in order to take advantage of some of Swift's features, NotificationBanner wasn't really built to be nicely compatible with Objective-C. Objective-C is not able to handle swift initializers that contain both optionals and non optionals which is exactly what NotificationBanner utilizes. If you decide to use Swift in any of your future projects, I hope you give NotificationBanner another try.

Thanks!

**Comment by bhartsb** [comment]
I've been able to use the StatusBarNotificationBanner by including the source files and dependent files for MarqueeLabel and SnapKit in my obj-c Xcode project.  In order for the bridging header to generate correctly I had to change these lines in the respective files:

`@objc public class StatusBarNotificationBanner: BaseNotificationBanner {
@objc public class NotificationBanner: BaseNotificationBanner {
@objc public class BaseNotificationBanner: UIView {
@objc public enum BannerStyle:Int {
@objc public enum QueuePosition: Int { 
`

Seems to be working.

**Comment by Daltron** [comment]
@bhartsb Thanks for the update. It's been awhile since I've worked with Swift CocoaPods in Objective-C so I'm glad you've explained what you've done. It sounds like your getting everything to work properly so that is great to hear!

**Comment by domhof** [comment]
I have created an Objective-C compatible fork here: https://github.com/domhof/NotificationBanner/tree/objc
