### ISSUE TITLE
Banners from the bottom?

### ISSUE THREAD

**Issue by scottcc** [Daltron/NotificationBanner#31]
Looks like a great library here. I'm considering a strange use case - may not fit with your intent, but figure I'll ask here. Feel free to close this feature request if it's too odd.

I'd like to have a custom view animatable from the bottom upwards. This alone would be good, but the *ultimate* trick-shot would be to tie it to a scroll view such that it only animates in when the scroll view is not scrolling. 

Let me know if either might fit with your thinking - if so, I might help implement it too.

Thanks!
./scc

**Comment by Daltron** [comment]
Hi @scottcc! 😄 Adding the ability to animate from the bottom is actually on my things to do before the next CocoaPods version! 👍 However, since your scroll view feature request is too specific of a use case, I am going to have to decline to include that in a feature release unless quite a few other users want the exact same functionality. You should most definitely be able to accomplish this yourself relatively easily without having to creating a fork. All you would have to do would be to listen to the scroll events on your scroll view and decide wether or not to display the banner after you create it. If you need to wait till scrolling stops, then save it in an instance variable and then show it when scrolling stops. Hope that helps!

**Comment by scottcc** [comment]
Thanks @Daltron - no problem on doing it myself with scroll events (I'll debounce it too). Can't wait to see the from-the-bottom work! I'm hoping to use a custom view (which has a couple labels, image and a button on it). Exciting!

**Comment by Daltron** [comment]
@scottcc I'll try to get this release within the next week or so! I'll let you know when I release! 👍

**Comment by scottcc** [comment]
Heck YES. Happy to try out branches via direct pod pointers to commits too.  🍻

**Comment by Daltron** [comment]
@scottcc Included in [v1.4.0](https://github.com/Daltron/NotificationBanner/releases/tag/1.4.0) release! 🎉

**Comment by scottcc** [comment]
Wow! I'll be working on this _today_. Thanks again @Daltron.

**Comment by scottcc** [comment]
First pass was solid, everything seems to work as advertised. I might play with the animation timeframes and possibly put a debouncer on when I show it but that's the fine touches. Thanks again!

**Comment by Daltron** [comment]
@scottcc Thanks for reporting back! I'm glad to hear it fits your needs. Let me know if there is anything else I can help you with! :smile
