### ISSUE TITLE
Scroll Speed in Subtitle

### ISSUE THREAD

**Issue by beeef** [Daltron/NotificationBanner#74]
Hello,

at first I want to say that I love your NotificationBanner framework, it's absolutely nice.

I wanted to know if it's possible to slow down the scroll speed if the Subtitle label is too long? It scrolls very fast and I'm nearly not able to read it.

**Comment by Daltron** [comment]
Hi @beeef! 😄 I'm glad to hear you are enjoying the library. The scroll speed of the subtitle is actually dynamically calculated based on how long the length of the subtitle text is and how long you are displaying the banner for. I do this because I want the entire text to be displayed before the banner dismisses. If you want to slow it down, I would suggest make the banner duration longer. Let me know if this helps!

**Comment by beeef** [comment]
Nice! Yeah, that fixed my problem. Thank you very much! :)

**Comment by Daltron** [comment]
@beeef No problem at all! 👍
