### ISSUE TITLE
How to keep banner up until User Dismissal?

### ISSUE THREAD

**Issue by james-ff** [Daltron/NotificationBanner#78]
Hello,

How would I go about setting up the status bar banner such that it would remain until dismissed (tapped / swiped) by the user? 

I see that the autoDismiss bool when set to false disables the dismiss actions provided to the user, this is the opposite of what I am looking for in my case.

Many Thanks

**Comment by Daltron** [comment]
Hi @james-ff! 😄 If you look at what happens when the `autoDismiss` property is set inside the [BaseNotificationBanner.swift](https://github.com/Daltron/NotificationBanner/blob/b1b450394832eb34e575ae1a13590f9ab7d3a0a0/NotificationBanner/Classes/BaseNotificationBanner.swift) class, you will see that `dismissOnTap` and `dismissOnSwipeUp` are set to false if `autoDismiss` is also set to false. All you need to do is this and you should be good to go:

```swift
banner.autoDismiss = false
banner.dismissOnTap = true
banner.dismissOnSwipeUp = true
```

Let me know if that is what you are looking for! 👍

**Comment by james-ff** [comment]
I see, undo the side effects of setting autoDismiss to false once it has been set. Thanks!
